language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/,grade'

script: "./gradlew clean build"

notifications:
  email:
    recipients: ymalan0101@gmail.com